[package]
name = "slab-core"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
nanoid = "0.4.0"
chrono = { version = "0.4.19", features = ["serde"] }

